name: NodeJs CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
      
    steps:
    - uses: actions/checkout@v2
    - name: Installing packages
      run: npm i
    - name: Build and run tests
      run: |
        npm run build
        npm run test
